config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks, except: :show
  devise_for :users
  patch "toggle/:id", to: "tasks#toggle", as: :toggle
  delete "all", to: "tasks#tasks_delete", as: :tasks_to_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :toggle]

  def index
    unless params[:q] || params[:search]
      @tasks = Task.all
    else
      if params[:q] == "high"
        @tasks = Task.all.order(priority: :desc)
      elsif params[:q] == "low"
        @tasks = Task.all.order(priority: :asc)
      elsif params[:q] == "older"
        @tasks = Task.all.order(created_at: :asc)
      elsif params[:q] == "recent"
        @tasks = Task.all.order(created_at: :desc)
      elsif params[:search][:i]
        @tasks = Task.all.where content: params[:search][:i]
      end
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(set_params)
    @task.user = current_user
    if params[:task][:priority] == "High"
      @task.priority = 3
    elsif params[:task][:priority] == "Normal"
      @task.priority = 2
    elsif params[:task][:priority] == "Low"
      @task.priority = 1
    end
    if @task.save
      redirect_to tasks_path
    else
      flash[:alert] = "Something wrong"
      render :new
    end

  end

  def edit
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(set_params)
      redirect_to tasks_path
    else
      flash[:alert] = "Something wrong"
      render :new
    end
  end

  def destroy
    @task.delete
    redirect_to tasks_path
  end

  def toggle
    value = @task.done
    @task.update(done: !value)
    redirect_to tasks_path
  end

  def tasks_delete
    Task.destroy_all
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_params
    params.require(:task).permit(
      :priority,
      :content,
      :user_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>

  <footer class="text-center text-lg-start bg-light text-muted fixed-bottom">
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      Andrés Hernández:
      <a href="https://github.com/aahrodriguez" target="_blank"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/aahrodriguez/" target="_blank"><i class="fab fa-linkedin"></i></a>
    </div>
  </footer>
<% end %>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "To Do", tasks_path, class:"navbar-brand"   %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Order By
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "High priority", tasks_path(q: "high"), class:"dropdown-item" %>
            <%= link_to "Low priority", tasks_path(q: "low"), class:"dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Older", tasks_path(q: "older"), class:"dropdown-item" %>
            <%= link_to "Recent", tasks_path(q: "recent"), class:"dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, class:"nav-link", method: :delete  %>
        </li>
        <li>
          <a href="https://github.com/aahrodriguez/to_do" target="_blank" class="btn btn-success">Show me the code</a>
        </li>
      </ul>

      <%= simple_form_for :search, url: tasks_path, method: "GET", html: { class: 'form-inline my-2 my-lg-0' } do |f| %>
        <%= f.input :i, input_html: {value: params[:search] ? params[:search][:i] : ""}, class: "form-control mr-sm-2", label:false, placeholder: "Search" %>
        <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0 ml-1" %>
      <% end %>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for (@task) do |f| %>
  <%= f.input :content %>
  <%= f.input :priority, :collection => [["Low", 1], ["Normal",2], ["High", 3] ] %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "tasks/form" %>

app/views/tasks/index.html.erb
<% unless @tasks.exists? %>
  <div class="d-flex justify-content-between"">
    <div>
    </div>
    <div>
      <%= link_to "Add Task",new_task_path, class: "btn btn-primary mb-1" %>

    </div>
  </div>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "1.jpg", class: "d-block w-100 h-75"  %>
      </div>
      <div class="carousel-item">
        <%= image_tag "2.jpg", class: "d-block w-100 h-75"  %>
      </div>
      <div class="carousel-item">
        <%= image_tag "3.jpg", class: "d-block w-100 h-75"  %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">check</th>
        <th scope="col">#</th>
        <th scope="col">Task</th>
        <th scope="col">Priority</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each_with_index do |task, i| %>
      <tr>
        <th scope="row">
          <%= link_to !task.done ? "Mark as done" : "Unmark as done", toggle_path(task), class: "btn #{!task.done ? 'btn-success' : 'btn-danger'} btn-sm", method: :patch, id:"done"  %>
        </th>
        <td><%= i + 1 %></td>
        <% if task.done%>
          <td><s><%= task.content %></s></td>
        <% else %>
          <td><%= task.content %></td>
        <% end %>
        <td>
          <% if task.priority == 3 %>
            <span class="bg-danger text-white">
              <%="High"%>
            </span>
          <% elsif task.priority == 2 %>
            <span class="bg-warning text-white">
              <%="Normal"%>
            </span>
          <% elsif task.priority == 1 %>
            <span class="bg-success text-white">
              <%="Low"%>
            </span>
          <% end %>
        </td>
        <td>
          <%= link_to "",edit_task_path(task), class:"fas fa-pencil-alt" %>
          <%= link_to "",task_path(task), method: :delete, class:"far fa-trash-alt ml-2" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-between">
    <div></div>
    <div>
      <%= link_to "Delete all",tasks_to_delete_path, class: "btn btn-danger mb-1", method: :delete %>
      <%= link_to "Add Task",new_task_path, class: "btn btn-primary mb-1" %>
    </div>
  </div>
<% end %>

app/views/tasks/new.html.erb
<%= render "tasks/form" %>